### ISSUE TITLE
Can't dismiss the about popover on the Covid-19 map

### ISSUE THREAD

**Issue by iamleeg** [beoutbreakprepared/COVID-19-data-mapping-pipeline#39]
Steps to reproduce:
1. navigate to https://www.healthmap.org/covid-19/
2. tap "about" in the bottom of the map
3. press the X in the top-right of the About This Map popover

Expected behaviour:
4. the popover disappears.

Actual behaviour:
4a. The popover does not disappear. This message is logged in the Javascript console in the browser:

ReferenceError: modalWrapper is not defined covid-19:347:7
    handleHideModal https://www.healthmap.org/covid-19/:347
    onclick https://www.healthmap.org/covid-19/#:1

Environment: Firefox 75.0 on Ubuntu 18.04

**Comment by lmanul** [comment]
Should be fixed now.
